"use client"

import { useCallback, useEffect, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import type { Request, RequestTask } from "@/types"
import { Card, CardContent } from "@workspace/ui/components/card"
import { Button } from "@workspace/ui/components/button"
import { Tag, formatTagLabel } from "@workspace/ui/components/tag"
import { Input } from "@workspace/ui/components/input"
import { Textarea } from "@workspace/ui/components/textarea"
import { Separator } from "@workspace/ui/components/separator"
import { PageHeader, PageTitle, PageDescription } from "@workspace/ui/components/page-header"
import {
  SourceBadge,
  getClassificationColorClass,
} from "@workspace/ui/components/status-badge"
import { TonePicker } from "@workspace/ui/components/tone-picker"
import type { Tone } from "@workspace/ui/components/tone-picker"

const ACCIDENTAL_YES = ["sure", "no problem", "happy to", "of course", "will do", "sounds good", "absolutely"]
const ANALYSIS_POLL_INTERVAL_MS = 2000
const ANALYSIS_TIMEOUT_MS = 20000

type RequestWithTaskRows = Request & {
  task_rows?: RequestTask[]
  project?: {
    hourly_rate?: number | null
  }
}

type EstimateDraft = {
  costMin: string
  costMax: string
}

type TaskDraft = {
  description: string
  max_hours: string
  min_hours: string
  name: string
}

type ReplyIntent = "approval" | "included" | "decline"

export default function RequestReviewPage() {
  const { id, requestId } = useParams<{ id: string; requestId: string }>()
  const router = useRouter()

  const [request, setRequest] = useState<RequestWithTaskRows | null>(null)
  const [reply, setReply] = useState("")
  const [replyTouched, setReplyTouched] = useState(false)
  const [replyAutoGenerated, setReplyAutoGenerated] = useState(true)
  const [tone, setTone] = useState<Tone>("professional")
  const [costMin, setCostMin] = useState("")
  const [costMax, setCostMax] = useState("")
  const [costTouched, setCostTouched] = useState(false)
  const [technicalBreakdown, setTechnicalBreakdown] = useState("")
  const [technicalBreakdownTouched, setTechnicalBreakdownTouched] = useState(false)
  const [effortMin, setEffortMin] = useState("")
  const [effortMax, setEffortMax] = useState("")
  const [effortTouched, setEffortTouched] = useState(false)
  const [taskDrafts, setTaskDrafts] = useState<TaskDraft[]>([])
  const [tasksTouched, setTasksTouched] = useState(false)
  const [generatingReply, setGeneratingReply] = useState(false)
  const [sending, setSending] = useState(false)
  const [sendError, setSendError] = useState("")
  const [analysing, setAnalysing] = useState(false)
  const [analysisError, setAnalysisError] = useState("")
  const [accidentalYes, setAccidentalYes] = useState(false)

  const loadRequest = useCallback(async function loadRequest() {
    const reqRes = await fetch(`/api/requests/${requestId}`)
    const reqData = await reqRes.json()

    if (!reqRes.ok) {
      throw new Error((reqData as { error?: string }).error ?? "Failed to load request")
    }

    setRequest(reqData)
    setAnalysisError(
      reqData.analysis_status === "failed"
        ? (reqData.analysis_error ?? "AI analysis failed. Please review the request and try again.")
        : ""
    )
    if (!replyTouched) {
      setReply(reqData.final_reply ?? reqData.draft_reply ?? "")
      setTone(reqData.reply_tone ?? "professional")
      setReplyAutoGenerated(!reqData.final_reply)
    }
    if (!costTouched) {
      setCostMin(formatCostInput(reqData.cost_min))
      setCostMax(formatCostInput(reqData.cost_max))
    }
    if (!technicalBreakdownTouched) {
      setTechnicalBreakdown(reqData.technical_breakdown ?? "")
    }
    if (!effortTouched) {
      setEffortMin(formatEstimateInput(reqData.effort_min_hours))
      setEffortMax(formatEstimateInput(reqData.effort_max_hours))
    }
    if (!tasksTouched) {
      setTaskDrafts((reqData.tasks ?? []).map((task: Request["tasks"][number]) => ({
        description: task.description ?? "",
        max_hours: String(task.max_hours ?? 0),
        min_hours: String(task.min_hours ?? 0),
        name: task.name ?? "",
      })))
    }
  }, [costTouched, effortTouched, replyTouched, requestId, tasksTouched, technicalBreakdownTouched])

  useEffect(() => {
    const timeout = window.setTimeout(() => {
      void loadRequest().catch((error) => {
        setAnalysisError(error instanceof Error ? error.message : "Failed to load request.")
      })
    }, 0)

    return () => window.clearTimeout(timeout)
  }, [loadRequest])

  const isAwaitingAnalysis = Boolean(
    request &&
      (request.analysis_status === "queued" || request.analysis_status === "running")
  )

  useEffect(() => {
    if (!request || !isAwaitingAnalysis) return

    let cancelled = false
    const deadline = new Date(request.created_at).getTime() + ANALYSIS_TIMEOUT_MS

    async function poll() {
      while (!cancelled) {
        await new Promise((resolve) => window.setTimeout(resolve, ANALYSIS_POLL_INTERVAL_MS))
        if (cancelled) return

        try {
          await loadRequest()
        } catch (error) {
          if (!cancelled) {
            setAnalysisError(error instanceof Error ? error.message : "Failed to refresh request analysis.")
          }
          return
        }

        if (Date.now() >= deadline && !cancelled) {
          setAnalysisError("AI analysis is taking longer than expected. You can review manually or try re-analysing.")
          return
        }
      }
    }

    void poll()

    return () => {
      cancelled = true
    }
  }, [isAwaitingAnalysis, loadRequest, request])

  async function reanalyse() {
    setAnalysing(true)
    setAnalysisError("")
    try {
      const res = await fetch('/api/ai/analyse', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ request_id: requestId }),
      })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        setAnalysisError((data as { error?: string }).error ?? "Analysis failed. Please try again.")
        return
      }
      await loadRequest()
    } catch (error) {
      setAnalysisError(error instanceof Error ? error.message : "Analysis failed. Please try again.")
    } finally {
      setAnalysing(false)
    }
  }

  function checkAccidentalYes(text: string) {
    const lower = text.toLowerCase()
    const isOutOfScope = request?.classification === "out_of_scope" || request?.classification === "ambiguous"
    if (!isOutOfScope) { setAccidentalYes(false); return }
    setAccidentalYes(ACCIDENTAL_YES.some((w) => lower.includes(w)))
  }

  function costValidationError(min = costMin, max = costMax) {
    const hasMin = Boolean(min.trim())
    const hasMax = Boolean(max.trim())
    if (!hasMin && !hasMax) return ""
    if (!hasMin || !hasMax) return "Enter both cost amounts or set both to 0 if this work is included."
    const parsedMin = parseCostInput(min)
    const parsedMax = parseCostInput(max)

    if (parsedMin === null || parsedMax === null) return "Cost amounts must use whole dollars."
    if (parsedMin < 0 || parsedMax < 0) return "Cost amounts cannot be negative."
    if (parsedMin > parsedMax) return "Minimum cost cannot be higher than maximum cost."

    return ""
  }

  function effortValidationError(min = effortMin, max = effortMax) {
    const hasMin = Boolean(min.trim())
    const hasMax = Boolean(max.trim())
    if (!hasMin && !hasMax) return ""
    if (!hasMin || !hasMax) return "Enter both effort amounts if you want to override the estimate."

    const parsedMin = parseEstimateInput(min)
    const parsedMax = parseEstimateInput(max)

    if (parsedMin === null || parsedMax === null) return "Effort estimates must use whole hours."
    if (parsedMin > parsedMax) return "Minimum effort cannot be higher than maximum effort."

    return ""
  }

  function tasksValidationError(nextTasks = taskDrafts) {
    for (const task of nextTasks) {
      const hasContent = Boolean(
        task.name.trim() ||
        task.description.trim() ||
        task.min_hours.trim() ||
        task.max_hours.trim()
      )
      if (!hasContent) continue

      const min = parseEstimateInput(task.min_hours)
      const max = parseEstimateInput(task.max_hours)
      if (!task.name.trim() || min === null || max === null || min > max) {
        return "Each task needs a name plus valid whole-hour min and max estimates."
      }
    }

    return ""
  }

  function getDefaultReplyIntent(nextCost: EstimateDraft = { costMin, costMax }): ReplyIntent {
    const min = parseCostInput(nextCost.costMin) ?? request?.cost_min ?? 0
    const max = parseCostInput(nextCost.costMax) ?? request?.cost_max ?? 0
    const requiresApproval = request?.classification !== "in_scope" && (min > 0 || max > 0)

    return requiresApproval ? "approval" : "included"
  }

  async function refreshAutoReply(
    nextTone = tone,
    nextCost: EstimateDraft = { costMin, costMax },
    intent: ReplyIntent = getDefaultReplyIntent(nextCost)
  ) {
    if (!request) return

    const costError = costValidationError(nextCost.costMin, nextCost.costMax)
    const effortError = effortValidationError()
    const taskError = tasksValidationError()
    if (costError) {
      setSendError(costError)
      return
    }
    if (effortError) {
      setSendError(effortError)
      return
    }
    if (taskError) {
      setSendError(taskError)
      return
    }

    setGeneratingReply(true)
    setSendError("")
    try {
      const res = await fetch(`/api/requests/${requestId}/reply`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          tone: nextTone,
          intent,
          current_reply: reply,
          cost_min: parseCostInput(nextCost.costMin),
          cost_max: parseCostInput(nextCost.costMax),
          technical_breakdown: technicalBreakdown,
          classification: request.classification,
          timeline_impact_days: request.timeline_impact_days,
        }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) {
        setSendError((data as { error?: string }).error ?? "Failed to generate the client reply.")
        return
      }

      const nextReply = (data as { reply?: string }).reply ?? ""
      setReply(nextReply)
      setReplyTouched(true)
      setReplyAutoGenerated(true)
      checkAccidentalYes(nextReply)
    } finally {
      setGeneratingReply(false)
    }
  }

  function handleToneChange(nextTone: Tone) {
    setTone(nextTone)
    void refreshAutoReply(nextTone)
  }

  function updateCost(which: "min" | "max", value: string) {
    const sanitized = value.replace(/[^\d]/g, "")

    setCostTouched(true)
    if (which === "min") {
      setCostMin(sanitized)
    } else {
      setCostMax(sanitized)
    }

  }

  function regenerateAfterCostChange() {
    if (replyAutoGenerated) {
      void refreshAutoReply(tone)
    }
  }

  function generateDeclineReply() {
    void refreshAutoReply(tone, { costMin, costMax }, "decline")
  }

  function updateEffort(which: "min" | "max", value: string) {
    const sanitized = value.replace(/[^\d]/g, "")
    setEffortTouched(true)
    if (which === "min") {
      setEffortMin(sanitized)
    } else {
      setEffortMax(sanitized)
    }
  }

  function updateTask(index: number, field: keyof TaskDraft, value: string) {
    setTasksTouched(true)
    setTaskDrafts((current) =>
      current.map((task, taskIndex) =>
        taskIndex === index
          ? {
              ...task,
              [field]:
                field === "min_hours" || field === "max_hours"
                  ? value.replace(/[^\d]/g, "")
                  : value,
            }
          : task
      )
    )
  }

  function addTask() {
    setTasksTouched(true)
    setTaskDrafts((current) => [
      ...current,
      { description: "", max_hours: "", min_hours: "", name: "" },
    ])
  }

  function removeTask(index: number) {
    setTasksTouched(true)
    setTaskDrafts((current) => current.filter((_, taskIndex) => taskIndex !== index))
  }

  function buildTaskPayload() {
    return taskDrafts
      .filter((task) => task.name.trim() || task.description.trim() || task.min_hours.trim() || task.max_hours.trim())
      .map((task) => ({
        name: task.name.trim(),
        description: task.description.trim(),
        min_hours: parseEstimateInput(task.min_hours) ?? 0,
        max_hours: parseEstimateInput(task.max_hours) ?? 0,
      }))
  }

  async function markReadyToShare() {
    if (!request) return

    const costError = costValidationError()
    const effortError = effortValidationError()
    const taskError = tasksValidationError()
    if (costError) {
      setSendError(costError)
      return
    }
    if (effortError) {
      setSendError(effortError)
      return
    }
    if (taskError) {
      setSendError(taskError)
      return
    }

    setSending(true)
    setSendError("")
    try {
      const res = await fetch(`/api/requests/${requestId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          status: "sent_to_client",
          final_reply: reply,
          tone,
          cost_min: parseCostInput(costMin),
          cost_max: parseCostInput(costMax),
          technical_breakdown: technicalBreakdown,
          effort_min_hours: parseEstimateInput(effortMin),
          effort_max_hours: parseEstimateInput(effortMax),
          tasks: buildTaskPayload(),
          classification: request.classification,
        }),
      })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        setSendError((data as { error?: string }).error ?? "Failed to send the Slack approval message. Please try again.")
        return
      }
      router.push(`/projects/${id}`)
    } catch (error) {
      setSendError(error instanceof Error ? error.message : "Failed to send the Slack approval message. Please try again.")
    } finally {
      setSending(false)
    }
  }

  async function updateStatus(status: string) {
    if (!request) return

    const effortError = effortValidationError()
    const taskError = tasksValidationError()
    if (effortError) {
      setSendError(effortError)
      return
    }
    if (taskError) {
      setSendError(taskError)
      return
    }

    setSendError("")
    const res = await fetch(`/api/requests/${requestId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        status,
        final_reply: reply,
        tone,
        technical_breakdown: technicalBreakdown,
        effort_min_hours: parseEstimateInput(effortMin),
        effort_max_hours: parseEstimateInput(effortMax),
        tasks: buildTaskPayload(),
        classification: request.classification,
      }),
    })
    if (!res.ok) {
      const data = await res.json().catch(() => ({}))
      setSendError((data as { error?: string }).error ?? "Failed to update request status.")
      return
    }
    router.push(`/projects/${id}`)
  }

  if (!request) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <p className="text-sm text-muted-foreground">Loading...</p>
      </div>
    )
  }

  const colorClass = getClassificationColorClass(request.classification)
  const taskRows = request.task_rows ?? []
  const completedTaskCount = taskRows.filter((task) => task.status === "completed").length
  const progressPercent = taskRows.length ? Math.round((completedTaskCount / taskRows.length) * 100) : 0
  const costError = costValidationError()
  const effortError = effortValidationError()
  const taskError = tasksValidationError()
  const requiresApproval =
    request.classification !== "in_scope" &&
    ((parseCostInput(costMin) ?? request.cost_min ?? 0) > 0 || (parseCostInput(costMax) ?? request.cost_max ?? 0) > 0)
  const classLabel: Record<string, string> = {
    out_of_scope: "OUT OF SCOPE",
    in_scope: "IN SCOPE",
    ambiguous: "AMBIGUOUS",
    clarification_needed: "CLARIFY",
  }
  const analysisStatusLabel: Record<string, string> = {
    queued: "QUEUED",
    running: "ANALYSING…",
    completed: "READY FOR REVIEW",
    failed: "ANALYSIS FAILED",
  }

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="px-6 py-6 border-b border-border">
        <PageHeader>
          <div>
            <PageTitle>Request Review</PageTitle>
            <PageDescription>
              Review the client&apos;s request against the agreed scope and prepare a client-ready response.
            </PageDescription>
          </div>
        </PageHeader>
      </div>

      {/* Two-panel layout */}
      <div className="flex gap-0 min-h-[calc(100vh-120px)]">

        {/* LEFT — Original request (60%) */}
        <div className="w-[60%] p-6 space-y-4">
          <div className="flex items-center justify-between">
            <p className="text-xs uppercase tracking-wider text-muted-foreground">
              Client Request
            </p>
            <SourceBadge source={request.source} />
          </div>

          {/* Request metadata */}
          <Card size="sm">
            <CardContent className="space-y-2">
              {([
                ["From", request.raw_email_from],
                ["Subject", request.raw_email_subject],
                ["Received", new Date(request.created_at).toLocaleString()],
              ] as [string, string | null][]).map(
                ([k, v]) =>
                  v && (
                    <div key={k} className="flex gap-3">
                      <span className="text-xs w-16 flex-shrink-0 text-muted-foreground/50">
                        {k}
                      </span>
                      <span className="text-xs text-muted-foreground">{v}</span>
                    </div>
                  )
              )}
            </CardContent>
          </Card>

          {/* Request body */}
          <Card>
            <CardContent>
              <pre className="text-sm whitespace-pre-wrap leading-relaxed text-foreground min-h-[200px]">
                {request.raw_email_body}
              </pre>
            </CardContent>
          </Card>
        </div>

        {/* Vertical divider */}
        <Separator orientation="vertical" />

        {/* RIGHT — AI Analysis (40%) */}
        <div className="w-[40%] p-6 space-y-5">

          {/* Panel header with re-analyse button */}
          <div className="flex items-center justify-between">
            <p className="text-xs uppercase tracking-wider text-muted-foreground">AI Analysis</p>
            <Button
              variant={!request?.classification ? "default" : "outline"}
              size="sm"
              onClick={reanalyse}
              disabled={analysing}
            >
              {analysing ? (
                <>
                  <span className="inline-block animate-spin">↻</span>
                  Analysing…
                </>
              ) : (
                <>↻ Re-analyse</>
              )}
            </Button>
          </div>

          {analysisError && (
            <Card className="border-destructive/30 bg-destructive/10">
              <CardContent className="text-xs text-destructive">
                {analysisError}
              </CardContent>
            </Card>
          )}

          {/* Classification panel */}
          <Card
            className={`border-l-4 ${colorClass}`}
          >
            <CardContent className="space-y-3">
              <span className="text-lg font-bold">
                {request.classification
                  ? classLabel[request.classification]
                  : analysisStatusLabel[request.analysis_status]}
              </span>
              {isAwaitingAnalysis && (
                <p className="text-xs text-muted-foreground">
                  Monad is still generating the classification and draft reply. You can keep reviewing manually while it runs.
                </p>
              )}
              {request.analysis_status === "failed" && (
                <p className="text-xs text-muted-foreground">
                  The latest AI run did not complete successfully. Review the request manually, then retry once the configuration or scope context is fixed.
                </p>
              )}
              {request.confidence !== null && (
                <div>
                  <div className="flex justify-between text-xs mb-1 text-muted-foreground">
                    <span>Confidence</span>
                    <span>{request.confidence}%</span>
                  </div>
                  <div className="h-1 rounded-full bg-border">
                    <div
                      className="h-1 rounded-full transition-all bg-primary"
                      style={{ width: `${request.confidence}%` }}
                    />
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Scope evidence */}
          {request.scope_evidence?.length > 0 && (
            <div>
              <p className="text-xs uppercase tracking-wider mb-2 text-muted-foreground">
                Evidence from original scope
              </p>
              <div className="space-y-2">
                {request.scope_evidence.map((quote, i) => (
                  <div
                    key={i}
                    className="px-3 py-2 rounded text-xs italic border-l-2 border-primary bg-primary/5 text-foreground"
                  >
                    &ldquo;{quote}&rdquo;
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Technical breakdown */}
          <div>
            <p className="text-xs uppercase tracking-wider mb-2 text-muted-foreground">
              What this actually involves
            </p>
            <Textarea
              value={technicalBreakdown}
              onChange={(event) => {
                setTechnicalBreakdownTouched(true)
                setTechnicalBreakdown(event.target.value)
              }}
              rows={5}
              placeholder="Summarise the implementation impact in plain English."
            />
          </div>

          {request.reasoning && (
            <div>
              <p className="text-xs uppercase tracking-wider mb-2 text-muted-foreground">
                AI reasoning
              </p>
              <p className="text-xs leading-relaxed text-muted-foreground">
                {request.reasoning}
              </p>
            </div>
          )}

          {/* Task breakdown */}
          <div>
            <div className="mb-2 flex items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-wider text-muted-foreground">
                Task Breakdown
              </p>
              <Button variant="outline" size="sm" onClick={addTask}>
                Add task
              </Button>
            </div>
            <div className="space-y-3">
              {taskDrafts.map((task, i) => (
                <Card key={i} size="sm">
                  <CardContent className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Input
                        value={task.name}
                        onChange={(event) => updateTask(i, "name", event.target.value)}
                        placeholder="Task name"
                      />
                      <Button variant="outline" size="sm" onClick={() => removeTask(i)}>
                        Remove
                      </Button>
                    </div>
                    <Textarea
                      value={task.description}
                      onChange={(event) => updateTask(i, "description", event.target.value)}
                      rows={2}
                      placeholder="Task description"
                    />
                    <div className="grid grid-cols-2 gap-2">
                      <Input
                        inputMode="numeric"
                        value={task.min_hours}
                        onChange={(event) => updateTask(i, "min_hours", event.target.value)}
                        placeholder="Min hours"
                      />
                      <Input
                        inputMode="numeric"
                        value={task.max_hours}
                        onChange={(event) => updateTask(i, "max_hours", event.target.value)}
                        placeholder="Max hours"
                      />
                    </div>
                  </CardContent>
                </Card>
              ))}
              {taskDrafts.length === 0 && (
                <p className="text-xs text-muted-foreground">
                  No tasks yet. Add the task split you want to track and share.
                </p>
              )}
            </div>
          </div>

          {taskRows.length > 0 && (
            <div>
              <div className="mb-2 flex items-center justify-between gap-3">
                <p className="text-xs uppercase tracking-wider text-muted-foreground">
                  Implementation Progress
                </p>
                <Tag variant={request.implementation_status === "completed" ? "primary" : "outline"}>
                  {completedTaskCount}/{taskRows.length} complete
                </Tag>
              </div>
              <div className="mb-2 h-1 rounded-full bg-border">
                <div
                  className="h-1 rounded-full bg-primary transition-all"
                  style={{ width: `${progressPercent}%` }}
                />
              </div>
              <div className="space-y-1">
                {taskRows.map((task) => (
                  <div key={task.id} className="flex items-start justify-between gap-2 py-1.5 border-b border-border last:border-0">
                    <div className="min-w-0">
                      <p className="text-xs font-medium text-foreground">{task.name}</p>
                      {task.description && (
                        <p className="text-xs text-muted-foreground mt-0.5">{task.description}</p>
                      )}
                    </div>
                    <Tag variant={task.status === "completed" ? "primary" : "outline"}>
                      {formatTagLabel(task.status)}
                    </Tag>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Effort & Cost */}
          <Card size="sm">
            <CardContent className="space-y-4">
              <div>
                <p className="text-xs mb-2 text-muted-foreground/50">Estimated effort</p>
                <div className="grid grid-cols-2 gap-2">
                  <Input
                    inputMode="numeric"
                    aria-label="Minimum estimated effort"
                    value={effortMin}
                    onChange={(event) => updateEffort("min", event.target.value)}
                    placeholder="Min hours"
                  />
                  <Input
                    inputMode="numeric"
                    aria-label="Maximum estimated effort"
                    value={effortMax}
                    onChange={(event) => updateEffort("max", event.target.value)}
                    placeholder="Max hours"
                  />
                </div>
              </div>
              <div>
                <p className="text-xs mb-2 text-muted-foreground/50">Additional cost to client</p>
                <div className="grid grid-cols-2 gap-2">
                  <Input
                    inputMode="numeric"
                    aria-label="Minimum estimated cost"
                    value={costMin}
                    onChange={(event) => updateCost("min", event.target.value)}
                    onBlur={regenerateAfterCostChange}
                    placeholder="Min"
                  />
                  <Input
                    inputMode="numeric"
                    aria-label="Maximum estimated cost"
                    value={costMax}
                    onChange={(event) => updateCost("max", event.target.value)}
                    onBlur={regenerateAfterCostChange}
                    placeholder="Max"
                  />
                </div>
                <p className="mt-2 text-xs text-muted-foreground">
                  Set both amounts to 0 to include this work without sending an approval request.
                </p>
              </div>
            </CardContent>
          </Card>

          {/* Timeline + Risk */}
          <div className="flex gap-3">
            {request.timeline_impact_days !== null && (
              <Tag variant="danger">+{request.timeline_impact_days} days</Tag>
            )}
            {request.risk_level && (
              <Tag variant="outline">
                {formatTagLabel(`${request.risk_level} risk`)}
              </Tag>
            )}
          </div>
        </div>
      </div>

      {/* Reply section */}
      <Separator />
      <div className="p-6 space-y-4">
        <div className="flex items-center justify-between">
          <p className="text-xs uppercase tracking-wider text-muted-foreground">
            Client Response
          </p>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => void refreshAutoReply()} disabled={generatingReply}>
              {generatingReply ? "Generating..." : "Regenerate"}
            </Button>
            <Button variant="outline" size="sm" onClick={generateDeclineReply} disabled={generatingReply}>
              {generatingReply ? "Generating..." : "Decline Draft"}
            </Button>
            <TonePicker value={tone} onChange={handleToneChange} />
          </div>
        </div>

        {accidentalYes && (
          <Card className="border-primary/30 bg-primary/10">
            <CardContent className="flex gap-3 items-start">
              <span>⚠️</span>
              <p className="text-xs text-[var(--amber-100)]">
                Your reply appears to accept out-of-scope work without mentioning cost or getting
                approval. Are you sure?
              </p>
            </CardContent>
          </Card>
        )}

        <Textarea
          value={reply}
          onChange={(e) => {
            setReplyTouched(true)
            setReplyAutoGenerated(false)
            setReply(e.target.value)
            checkAccidentalYes(e.target.value)
          }}
          rows={8}
        />

        {(sendError || costError || effortError || taskError) && (
          <Card className="border-destructive/30 bg-destructive/10">
            <CardContent className="flex gap-3 items-center">
              <span className="text-destructive text-xs">{sendError || costError || effortError || taskError}</span>
            </CardContent>
          </Card>
        )}

        <div className="flex items-center justify-between">
          <div className="flex gap-3">
            <Button variant="outline" size="sm" onClick={() => updateStatus("accepted_in_scope")}>
              Mark as In-Scope
            </Button>
            <Button variant="outline" size="sm" onClick={() => updateStatus("deferred")}>
              Defer
            </Button>
            <Button variant="destructive" size="sm" onClick={() => updateStatus("declined")}>
              Decline
            </Button>
          </div>
          <Button
            onClick={markReadyToShare}
            disabled={sending || generatingReply || !reply.trim() || Boolean(costError) || Boolean(effortError) || Boolean(taskError)}
          >
            {sending ? "Sending to Slack..." : requiresApproval ? "Send for approval →" : "Share with client →"}
          </Button>
        </div>
      </div>
    </div>
  )
}

function formatCostInput(value: number | null) {
  return typeof value === "number" ? String(value) : ""
}

function parseCostInput(value: string) {
  if (!value.trim()) return null

  const parsed = Number(value)
  return Number.isInteger(parsed) ? parsed : null
}

function formatEstimateInput(value: number | null) {
  return typeof value === "number" ? String(value) : ""
}

function parseEstimateInput(value: string) {
  if (!value.trim()) return null

  const parsed = Number(value)
  return Number.isInteger(parsed) ? parsed : null
}
